language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - nightly

matrix:
  allow_failures:
  - julia: nightly

notifications:
  email: false

addons:
  apt_packages:
    - gfortran
    
after_success:
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder());  Codecov.submit(process_folder())'
