name = "ReverseMcCormick"
uuid = "f9d89e60-3bef-4186-aa8f-bdf0d7614dd6"
authors = ["Matthew Wilhelm <matthew.wilhelm@uconn.edu>"]
version = "0.8.2"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
IntervalContractors = "15111844-de3b-5229-b4ba-526f2f385dc9"
McCormick = "53c679d3-6890-5091-8386-c291e8c8aaa1"

[compat]
DocStringExtensions = "~0.8"
IntervalContractors = "~0.3, ~0.4"
McCormick = "0.9.2, ~0.10"
julia = "~1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
